language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
env:
    - DJANGO_PACKAGE="Django>=1.5,<1.6"
    - DJANGO_PACKAGE="Django>=1.6,<1.7"
    - DJANGO_PACKAGE="https://www.djangoproject.com/download/1.7b3/tarball/"

install: pip install $DJANGO_PACKAGE markdown docutils --use-mirrors

# Make sure migrations can be made (see issue: #20 https://github.com/jamesturk/django-markupfield/issues/20)
before_script: ./if_django1.7.py django-admin.py makemigrations --settings=markupfield.tests.settings --pythonpath=.

script: django-admin.py test --settings=markupfield.tests.settings --pythonpath=.

notifications:
    email:
        - travis@matt3o12.de
